In [193]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [194]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/startup_funding.csv',encoding='utf-8-sig')
print(df.shape)
df.head()

(3044, 10)

,Sr No,Date dd/mm/yyyy,Startup Name,Industry Vertical,SubVertical,City Location,Investors Name,InvestmentnType,Amount in USD,Remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN

In [195]:
df.info()
df.isna().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Sr No              3044 non-null   int64
 1   Date dd/mm/yyyy    3044 non-null   object
 2   Startup Name       3044 non-null   object
 3   Industry Vertical  2873 non-null   object
 4   SubVertical        2108 non-null   object
 5   City  Location     2864 non-null   object
 6   Investors Name     3020 non-null   object
 7   InvestmentnType    3040 non-null   object
 8   Amount in USD      2084 non-null   object
 9   Remarks            419 non-null    object
dtypes: int64(1), object(9)
memory usage: 237.9+ KB

Sr No                   0
Date dd/mm/yyyy         0
Startup Name            0
Industry Vertical     171
SubVertical           936
City  Location        180
Investors Name         24
InvestmentnType         4
Amount in USD         960
Remarks              2625
dtype: int64

In [196]:
df.duplicated().sum()

np.int64(0)

In [197]:
df.columns

Index(['Sr No', 'Date dd/mm/yyyy', 'Startup Name', 'Industry Vertical',
       'SubVertical', 'City  Location', 'Investors Name', 'InvestmentnType',
       'Amount in USD', 'Remarks'],
      dtype='object')

In [198]:
df.columns = ['sr_no', 'date', 'startup_name', 'industry', 'subvertical', 'city', 'investors', 'investment_type', 'amount_usd', 'remarks']
df.head(10)

,sr_no,date,startup_name,industry,subvertical,city,investors,investment_type,amount_usd,remarks
0,1,09/01/2020,BYJU’S,E-Tech,E-learning,Bengaluru,Tiger Global Management,Private Equity Round,"20,00,00,000",NaN
1,2,13/01/2020,Shuttl,Transportation,App based shuttle service,Gurgaon,Susquehanna Growth Equity,Series C,"80,48,394",NaN
2,3,09/01/2020,Mamaearth,E-commerce,Retailer of baby and toddler products,Bengaluru,Sequoia Capital India,Series B,"1,83,58,860",NaN
3,4,02/01/2020,https://www.wealthbucket.in/,FinTech,Online Investment,New Delhi,Vinod Khatumal,Pre-series A,"30,00,000",NaN
4,5,02/01/2020,Fashor,Fashion and Apparel,Embroiled Clothes For Women,Mumbai,Sprout Venture Partners,Seed Round,"18,00,000",NaN
5,6,13/01/2020,Pando,Logistics,"Open-market, freight management platform",Chennai,Chiratae Ventures,Series A,"90,00,000",NaN
6,7,10/01/2020,Zomato,Hospitality,Online Food Delivery Platform,Gurgaon,Ant Financial,Private Equity Round,"15,00,00,000",NaN
7,8,12/12/2019,Ecozen,Technology,Agritech,Pune,Sathguru Catalyzer Advisors,Series A,"60,00,000",NaN
8,9,06/12/2019,CarDekho,E-Commerce,Automobile,Gurgaon,Ping An Global Voyager Fund,Series D,"7,00,00,000",NaN
9,10,03/12/2019,Dhruva Space,Aerospace,Satellite Communication,Bengaluru,"Mumbai Angels, Ravikanth Reddy",Seed,"5,00,00,000",NaN

In [199]:
bad = pd.to_datetime(df['date'],format = '%d/%m/%Y', errors = 'coerce').isna()
df.loc[bad,'date']

192               05/072018
2571              01/07/015
2606    \\xc2\\xa010/7/2015
2775             12/05.2015
2776             12/05.2015
2831             13/04.2015
3011             15/01.2015
3029            22/01//2015
Name: date, dtype: object

In [200]:
d = df['date'].str.replace(r'\\+xc2\\+xa0', '', regex=True)
d = d.str.replace(r'[./]+', '/', regex=True)
d = d.str.replace(r'^(\d{2}/\d{2})(\d{4})$', r'\1/\2', regex=True)
d = d.str.replace(r'/0(\d{2})$', r'/20\1', regex=True)
df['date'] = pd.to_datetime(d, format='%d/%m/%Y')
df['date'].dtype

dtype('<M8[ns]')

In [201]:
df.loc[~df['amount_usd'].str.fullmatch(r'[\d,]+', na=False) & df['amount_usd'].notna(), 'amount_usd'].unique()

array(['undisclosed', 'unknown', 'Undisclosed', '48,89,975.54',
       '27,39,034.68', '1,51,09,500.00', '14,342,000+',
       '\\\\xc2\\\\xa020,000,000', '\\\\xc2\\\\xa016,200,000',
       '\\\\xc2\\\\xa0N/A', '\\\\xc2\\\\xa0600,000',
       '\\\\xc2\\\\xa0685,000', '\\\\xc2\\\\xa019,350,000',
       '\\\\xc2\\\\xa05,000,000', '\\\\xc2\\\\xa010,000,000'],
      dtype=object)

In [202]:
a = df['amount_usd'].str.replace(r'\\+xc2\\+xa0', '', regex=True)
a = a.str.replace(r'[,+]', '', regex=True)
df['amount_usd'] = pd.to_numeric(a, errors='coerce')
df['amount_usd'].dtype

dtype('float64')

In [203]:
df['city'].value_counts().head(40)

city
Bangalore              700
Mumbai                 567
New Delhi              421
Gurgaon                287
Bengaluru              141
Pune                   105
Hyderabad               99
Chennai                 97
Noida                   92
Gurugram                50
Ahmedabad               38
Delhi                   34
Jaipur                  30
Kolkata                 21
Indore                  13
Chandigarh              11
Vadodara                10
Goa                     10
Singapore                8
Coimbatore               5
Pune / US                4
\\xc2\\xa0Gurgaon        4
Kanpur                   4
Nagpur                   3
\\xc2\\xa0New Delhi      3
Bhopal                   3
Faridabad                3
Ahemadabad               2
San Francisco            2
Kormangala               2
India/US                 2
Mumbai/Bengaluru         2
Gwalior                  2
Trivandrum               2
Surat                    2
Udupi                    2
Siliguri                 2
Bangalore/ Bangkok       2
Agra                     2
Kochi                    2
Name: count, dtype: int64

In [204]:
c= df['city'].str.replace(r'\\+xc2\\+xa0','',regex=True).str.strip()
c= c.str.split(r'\s*/\s*',regex=True).str[0]
c= c.replace({'Bangalore':'Bengaluru', 'Gurgaon': 'Gurugram', 'Delhi': 'New Delhi', 'Ahemadabad':'Ahmedabad', 'Trivandrum':'Thiruvananthapuram'})

df['city']=c.fillna('Unknown')
df['city'].value_counts().head(15)

city
Bengaluru     849
Mumbai        573
New Delhi     462
Gurugram      342
Unknown       180
Pune          112
Hyderabad     100
Chennai        98
Noida          94
Ahmedabad      40
Jaipur         30
Kolkata        21
Indore         13
Chandigarh     11
Goa            11
Name: count, dtype: int64

In [205]:
df['investment_type'].value_counts()

investment_type
Private Equity                 1356
Seed Funding                   1355
Seed/ Angel Funding              60
Seed / Angel Funding             47
Seed\\nFunding                   30
Debt Funding                     25
Series A                         24
Seed/Angel Funding               23
Series B                         20
Series C                         14
Series D                         12
Angel / Seed Funding              8
Seed Round                        7
Seed                              4
Private Equity Round              4
Pre-Series A                      4
Seed / Angle Funding              3
Equity                            2
Series E                          2
Corporate Round                   2
Venture Round                     2
Series F                          2
pre-Series A                      2
Seed Funding Round                1
Single Venture                    1
Maiden Round                      1
pre-series A                      1
Funding Round                     1
Series G                          1
Series H                          1
Venture                           1
Pre-series A                      1
Debt and Preference capital       1
Debt                              1
Bridge Round                      1
Angel Round                       1
Venture - Series Unknown          1
Series J                          1
Angel                             1
Series B (Extension)              1
Mezzanine                         1
Debt-Funding                      1
Pre Series A                      1
Inhouse Funding                   1
Equity Based Funding              1
Seed funding                      1
Private Funding                   1
Private                           1
Structured Debt                   1
PrivateEquity                     1
Term Loan                         1
Angel Funding                     1
Private\\nEquity                  1
Crowd funding                     1
Crowd Funding                     1
Name: count, dtype: int64

In [206]:
def fix_type(x):
    if pd.isna(x):
        return 'Unknown'
    t = x.lower()
    if 'pre' in t and 'series a' in t:
        return 'Pre-Series A'
    for L in 'abcdefghij':
        if 'series ' + L in t:
            return 'Series ' + L.upper()
    if 'seed' in t or 'angel' in t or 'angle' in t:
        return 'Seed/Angel'
    if 'debt' in t or 'loan' in t or 'mezzanine' in t:
        return 'Debt'
    if 'private' in t or 'equity' in t:
        return 'Private Equity'
    if 'crowd' in t:
        return 'Crowdfunding'
    return 'Other'

df['investment_type'] = df['investment_type'].apply(fix_type)
df['investment_type'].value_counts()

investment_type
Seed/Angel        1542
Private Equity    1367
Debt                31
Series A            24
Series B            21
Series C            14
Series D            12
Other               11
Pre-Series A         9
Unknown              4
Series F             2
Series E             2
Crowdfunding         2
Series G             1
Series H             1
Series J             1
Name: count, dtype: int64

In [207]:
print(df['industry'].nunique())
df['industry'].value_counts().head(50)

821

industry
Consumer Internet                    941
Technology                           478
eCommerce                            186
Healthcare                            70
Finance                               62
ECommerce                             61
Logistics                             32
E-Commerce                            29
Education                             24
Food & Beverage                       23
Ed-Tech                               14
E-commerce                            12
FinTech                                9
IT                                     8
Ecommerce                              8
Others                                 6
Real Estate                            6
Food and Beverage                      6
Fin-Tech                               6
Online Food Delivery                   5
Health and Wellness                    5
Logistics Tech                         5
Online Education Platform              5
Transport                              4
Transportation                         4
Food                                   3
Services                               3
Automobile                             3
EdTech                                 3
Social Media                           3
Food & Beverages                       3
Information Technology                 3
Food and Beverages                     3
Food Delivery Platform                 3
Big Data & Analytics platform          3
SaaS                                   3
ecommerce                              3
Hyperlocal Handyman Services           3
FMCG                                   3
Travel Tech                            2
Logistics Tech Platform                2
Online Marketplace                     2
Auto                                   2
Online Grocery platform                2
Hyper-Local Online/Mobile Grocery      2
Online budget hotel chain              2
Cab rental Mobile app                  2
Financial Tech                         2
Mobile Fitness App                     2
Car & Bike ecommerce platform          2
Name: count, dtype: int64

In [208]:
k = df['industry'].str.lower().str.replace(r'[^a-z]', '', regex=True)

mapping = {'ecommerce':'eCommerce', 'edtech':'EdTech', 'fintech':'FinTech',
           'foodbeverage':'Food & Beverage', 'foodandbeverage':'Food & Beverage',
           'foodbeverages':'Food & Beverage', 'foodandbeverages':'Food & Beverage',
           'it':'Technology', 'informationtechnology':'Technology',
           'transport':'Transportation', 'others':'Other'}

df['industry'] = k.map(mapping).fillna(df['industry']).fillna('Unknown')
df['industry'].nunique()

806

In [209]:
df['industry'].value_counts().head(60)

industry
Consumer Internet                                          941
Technology                                                 489
eCommerce                                                  299
Unknown                                                    171
Healthcare                                                  70
Finance                                                     62
Food & Beverage                                             35
Logistics                                                   32
Education                                                   24
EdTech                                                      20
FinTech                                                     16
Transportation                                               8
Other                                                        6
Real Estate                                                  6
Logistics Tech                                               5
Online Food Delivery                                         5
Health and Wellness                                          5
Online Education Platform                                    5
SaaS                                                         3
Food                                                         3
Hyperlocal Handyman Services                                 3
FMCG                                                         3
Social Media                                                 3
Food Delivery Platform                                       3
Big Data & Analytics platform                                3
Automobile                                                   3
Services                                                     3
Online Marketplace                                           2
Two-Wheeler Taxi Service                                     2
Travel Tech                                                  2
Online budget hotel chain                                    2
Mobile Fitness App                                           2
Customer Engagement Platform                                 2
Financial Tech                                               2
Hyper-Local Online/Mobile Grocery                            2
Cab rental Mobile app                                        2
Health & Fitness App                                         2
Inspiration                                                  2
Used Car Marketplace                                         2
Car & Bike ecommerce platform                                2
Digital / Mobile Wallet                                      2
Auto                                                         2
Online Grocery platform                                      2
Logistics Tech Platform                                      2
Job Search Platform                                          2
Online Payment Gateway                                       2
B2B                                                          2
Hyperlocal services marketplace                              2
Consumer Goods                                               2
Fashion Discovery platform                                   2
Online food ordering & Delivery service                      2
Interface development platform for Government officials      2
Gaming                                                       2
Online Logistics Platform                                    2
Hospitality                                                  2
Online Hiring Platform                                       2
Tech                                                         2
Home services marketplace                                    2
Health Care                                                  2
Waste Management Service                                     2
Name: count, dtype: int64

In [210]:
print(df['startup_name'].str.contains(r'\\+x|\\+n',regex=True).sum())
print(df['investors'].str.contains(r'\\+x|\\+n',regex=True, na=False).sum())

27
92

In [211]:
df[df['startup_name'].str.contains(r'\\+x|\\+n',regex=True)]['startup_name']

239                     What\\xe2\\x80\\x99s Up Life
712                             Byju\\xe2\\x80\\x99s
713                  Creator\\xe2\\x80\\x99s Gurukul
983                             Byju\\xe2\\x80\\x99s
1153                            SERV\\xe2\\x80\\x99D
1164                            BYJU\\xe2\\x80\\x99s
1356                            Byju\\xe2\\x80\\x99s
1394                           \\xc2\\xa0CloudCherry
1398                         Let\xe2\x80\x99s Barter
1514           Don\\xe2\\x80\\x99t Scratch Your Head
1880                            Byju\\xe2\\x80\\x99s
2013                                 Alef\\nMobitech
2018                            PlanMy\\nMedicalTrip
2495                         Carl\\xe2\\x80\\x99s Jr
2504    NearBuy (previously\\xc2\\xa0 groupon India)
2602                        \\xc2\\xa0News in shorts
2603                             \\xc2\\xa0Bluestone
2604                              \\xc2\\xa0Shopsity
2605                              \\xc2\\xa0Notesgen
2606                    \\xc2\\xa0Infinity Assurance
2607                  \\xc2\\xa0Footprints Education
2608                        \\xc2\\xa0Loylty Rewards
2609                                 \\xc2\\xa0Ameyo
2610                              \\xc2\\xa0Mamagoto
2611                             \\xc2\\xa0Satvacart
2794                             \\xc2\\xa0Nudgespot
2954                           Faaso\\xe2\\x80\\x99s
Name: startup_name, dtype: object

In [212]:
df[df['investors'].str.contains(r'\\+x|\\+n',regex=True,na=False)]['investors'].head(30)

112     India Quotient and LetsVenture\\xe2\\x80\\x99s...
116     Sequoia India, Hillhouse Capital, Alphabet\\xe...
127     Norwest Venture Partners, CDC Group, the UK\\x...
141     Lakestar and Jungle Ventures, Softbank\\xe2\\x...
152     DST Global and Lightspeed Venture Partners\\xe...
157                                        KDDI\\xc2\\xa0
160     CLP Holdings Group, Innogy, \\xc3\\x98rstead, ...
163     Vertex Ventures Southeast Asia (SEA) and India...
182                               CDC Group plc\\xc2\\xa0
404     Sunil Kant Munjal, Hero Electronix\\xe2\\x80\\...
482     Titan Co Ltd, Tata Group\\xe2\\x80\\x99s watch...
660                       Undisclosed HNI\\xe2\\x80\\x99s
672     Accel Partners, IDG Ventures, Kalaari Capital,...
791       Falcon Edge Capital,\\xc2\\xa0 Capital Advisers
809     Vellayan Subbiah, Jonathan Boutelle, Rajan Ana...
842            Lahiri Music\\xe2\\x80\\x99s family office
874                             Labruyere Eberl\\xc3\\xa9
878     Accel Partners, Nandan Nilekani\\xe2\\x80\\x99...
968                              L\\xe2\\x80\\x99Occitane
994     B Capital Group, Ignition Partners, Greycroft,...
1073    Tencent,\\xc2\\xa0 ru-Net, RSI Fund, Thrive Ca...
1099    Sharad Sharma, Rajan Anandan,\\xc2\\xa0 Amit R...
1131    Venk Krishnan, MJ Aravind, Vikram Kotak, Jayan...
1166    Indian Angel Network, Let\\xe2\\x80\\x99s Venture
1186           RB Investments,\\xc2\\xa0 Kaleden Holdings
1232    Delta Partners, Sequoia India,\\xc2\\xa0 Mayfi...
1271    Vijay Shekhar Sharma, Pravin Gandhi,\\xc2\\xa0...
1289    GrowX Ventures, Sunil Kalra, Arun Venkatachala...
1300    ByteDance, Arun Sarin, Matrix Partners, Sequoi...
1350    Venturra Capital, Sequoia India, Susquehanna I...
Name: investors, dtype: object

In [213]:
import re

def decode_junk(m):
    hexes = re.findall(r'x([0-9a-fA-F]{2})', m.group())
    return bytes(int(h, 16) for h in hexes).decode('utf-8', errors='ignore')

for col in ['startup_name', 'subvertical', 'investors', 'remarks']:
    s = df[col].str.replace(r'(?:\\+x[0-9a-fA-F]{2})+', decode_junk, regex=True)
    s = s.str.replace(r'\\+n', ' ', regex=True)
    df[col] = s.str.replace(r'\s+', ' ', regex=True).str.strip()

print(df['startup_name'].str.contains(r'\\+x|\\+n', regex=True).sum())
print(df['investors'].str.contains(r'\\+x|\\+n', regex=True, na=False).sum())

0
0

In [214]:
df.isna().sum()

sr_no                 0
date                  0
startup_name          0
industry              0
subvertical         936
city                  0
investors            24
investment_type       0
amount_usd          971
remarks            2625
dtype: int64

In [215]:
df['investors']=df['investors'].fillna('Undisclosed')
df['subvertical']=df['subvertical'].fillna('Not provided')
df['remarks']=df['remarks'].fillna('Not provided')
df.isna().sum()

sr_no                0
date                 0
startup_name         0
industry             0
subvertical          0
city                 0
investors            0
investment_type      0
amount_usd         971
remarks              0
dtype: int64

In [216]:
df[df['startup_name'].str.contains(r'http|www',regex=True)]['startup_name']

3    https://www.wealthbucket.in/
Name: startup_name, dtype: object

In [217]:
df['startup_name']=(df['startup_name'].str.replace(r'^https?://(www\.)?','',regex=True).str.rstrip('/'))
df.loc[df['startup_name'].str.contains('wealthbucket'),'startup_name']

3    wealthbucket.in
Name: startup_name, dtype: object

In [219]:
df.info()
print(df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3044 entries, 0 to 3043
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   sr_no            3044 non-null   int64
 1   date             3044 non-null   datetime64[ns]
 2   startup_name     3044 non-null   object
 3   industry         3044 non-null   object
 4   subvertical      3044 non-null   object
 5   city             3044 non-null   object
 6   investors        3044 non-null   object
 7   investment_type  3044 non-null   object
 8   amount_usd       2073 non-null   float64
 9   remarks          3044 non-null   object
dtypes: datetime64[ns](1), float64(1), int64(1), object(7)
memory usage: 237.9+ KB
0

In [220]:
df.to_csv('/content/drive/MyDrive/cleaned_startup_funding.csv',index=False)
from google.colab import files
files.download('/content/drive/MyDrive/cleaned_startup_funding.csv')